POST http://localhost:8080/api/relationships
Content-Type: application/json

{
  "fromId": "fc3bb0c5-e4b2-47bc-8155-3c09c607bc21",
  "fromRole": "EMPLOYER",
  "toId": "36b3f268-82c4-4ef0-a15c-d89994983ee9",
  "toRole": "EMPLOYEE",
  "name": "EMPLOYMENT"
}

