POST http://localhost:8080/api/relationships
Content-Type: application/json

{
  "fromId": "3d1f1f7e-ce71-49f1-a2c9-4d82436ff5d0",
  "fromRole": "A",
  "toId": "44ba70bc-3e14-4532-afbc-31f6bd471e31",
  "toRole": "B",
  "name": "JUST_TRY"
}

