POST http://localhost:8080/api/relationships
Content-Type: application/json

{
  "fromId": "040b862e-2e2c-46d8-85e8-d3552ca8a052",
  "fromRole": "A",
  "toId": "e24bb174-fed4-4da2-b08c-06e883312d69",
  "toRole": "B",
  "name": "EMPLOYMENT"
}

