POST http://localhost:8080/api/persons
Content-Type: application/json

{
  "firstName": "Jan",
  "lastName": "Kowalski",
  "roles": ["EMPLOYEER", "ADMIN"],
  "registeredIdentifiers": [
    { "type": "PERSONAL_IDENTIFICATION_NUMBER", "number": "90010112345" }
  ]
}

