POST http://localhost:8080/api/persons
Content-Type: application/json

{
  "firstName": "Tomasz",
  "lastName": "Ogórek",
  "roles": ["EMPLOYEE"],
  "registeredIdentifiers": [
    { "type": "PERSONAL_IDENTIFICATION_NUMBER", "number": "32132132122" }
  ]
}

