POST http://localhost:8080/api/persons
Content-Type: application/json

{
  "firstName": "Aaa",
  "lastName": "Majtek",
  "roles": ["EMPLOYER"],
  "registeredIdentifiers": [
    { "type": "PERSONAL_IDENTIFICATION_NUMBER", "number": "98765432132" }
  ]
}

